import Header from "@/components/Header/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div style={{background: "white"}}>
      <Header />
      <div style={{ height: "90vh", overflowY: "auto" }}>{children}</div>
    </div>
  );
}
