import type { Metadata } from "next";
import "./globals.css";
import RootContainer from "@/components/RootContainer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <RootContainer>{children}</RootContainer>
      </body>
    </html>
  );
}
